### ISSUE TITLE
Create a mapping between the VDC geo codes for NepalMap and the names of VDCs in the census data files

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/maptools#11]
Each of the VDCs that are in the census-data CSV files need to be mapped to the unique geo code for each VDC in NepalMap.

The NepalMap codes for each VDC are in the `vdc_geo_code` column in [this file](https://github.com/Code4Nepal/geo/blob/master/vdcs-from-geojson.csv).

Many of them will be easy because the name in the census-data files is the same as the name in the `vdc` column in [vdcs-from-geojson.csv](https://github.com/Code4Nepal/geo/blob/master/vdcs-from-geojson.csv). That name was taken from the geo data files downloaded from http://gadm.org/. However, not all mappings will be easy. Some mappings will require a person to manually choose.

I think we need a python dictionary that looks something like this:

```python
vdc_geo_code_mappings = {
    'SomeDistrictName': {
        'FIRSTVDCFORTHATDISTRICT': 'this-VDCs-geo-code-for-nepalmap',
        'ANOTHERVDCFORTHATDISTRICT': 'this-VDCs-geo-code-for-nepalmap'
    },
    'Accham': {
        'BABALA': '2274',
        'BAIJINATH': '2275'
    },
    'Arghakhanchi': {
        'ADGURI': '3571'
    }
}
```

The district name key in the dictionary (like `Accham` above) should be the name of the district directory in the census-data project. the VDC name key in the nested dictionaries (like `BABALA` above) should be the value in the VDC/MUNICIPALITY column in the census-data CSV files. The geo code value (like `2274` above) should be the value in the  `vdc_geo_code` column in the [vdcs-from-geojson.csv](https://github.com/Code4Nepal/geo/blob/master/vdcs-from-geojson.csv) file.

**Comment by amitness** [comment]
Solved by [PR 13](https://github.com/Code4Nepal/geo/pull/13)

**Comment by cliftonmcintosh** [comment]
@studenton 

There are a couple of duplicates in the mappings, and I want to check with you about what to do with them.

In the Syangja district, two VDCs are mapped to the code 3468:
"BANGSING DEURALI": 3468,
"BENETHOK DEURALI": 3468

I think BANGSING DEURALI can be mapped to 3522, which is "Wangsing Deurali" in the vdcs-from-geojson.csv

In Ramechhap, there are two VDCs mapped to code 650:
"BHALUWAJOR": 650,
"GAGAL BHADAURE": 650

I think BHALUWAJOR can be mapped to 680, which is "Maluwajor" in the vdcs-from-geojson.csv

I will proceed with this change. Please let me know if you think that is incorrect.

**Comment by amitness** [comment]
Yes, please proceed.
